packages:
  - "apps/*"
  - "packages/*"
overrides:
  deepmerge-ts@<8.0.0: ">=8.0.0"
  mysql2@<3.22.0: ">=3.22.0"
allowBuilds:
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true
  unrs-resolver: true
