import { render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import GuidePage from "./page";

// The committed manifest is regenerated by `pnpm help:screens` — tests pin
// their own fixture so they exercise both branches (step with a capture /
// step without) regardless of what the artifact currently contains.
vi.mock("@/lib/help-screens.manifest.json", () => ({
  default: {
    "record-consumption": {
      "1": {
        stepTitle: "Site",
        mobile: {
          image: "/help-screens/record-consumption/1.mobile.png",
          imageW: 390,
          imageH: 844,
          target: { x: 20, y: 300, w: 350, h: 44 },
        },
        desktop: {
          image: "/help-screens/record-consumption/1.desktop.png",
          imageW: 1280,
          imageH: 800,
          target: { x: 400, y: 200, w: 480, h: 44 },
        },
      },
    },
  },
}));

async function renderGuidePage(guideId: string) {
  const element = await GuidePage({ params: Promise.resolve({ guideId }) });
  render(element);
}

describe("GuidePage screenshots", () => {
  it("renders the annotated screenshot for a step with a manifest entry", async () => {
    await renderGuidePage("record-consumption");

    // Step index 1 ("Site") has a capture: one image per viewport variant.
    const images = screen.getAllByRole("img", { name: /"Site" highlighted/ });
    expect(images).toHaveLength(2);
    expect(images[0]).toHaveAttribute("src", "/help-screens/record-consumption/1.mobile.png");
    expect(images[1]).toHaveAttribute("src", "/help-screens/record-consumption/1.desktop.png");
  });

  it("renders steps without a manifest entry text-only, exactly as before", async () => {
    await renderGuidePage("record-consumption");

    // Every other step of this guide has no capture — no other imgs appear.
    expect(screen.getAllByRole("img")).toHaveLength(2);
    // The text-only steps still render their full card content.
    expect(screen.getByText("Open Movements")).toBeInTheDocument();
    expect(screen.getByText("Record Consumption")).toBeInTheDocument();
  });

  it("renders a guide with no manifest entries at all with zero screenshots", async () => {
    await renderGuidePage("create-site");

    expect(screen.queryByRole("img")).not.toBeInTheDocument();
    expect(screen.getByRole("heading", { name: "How to create a site" })).toBeInTheDocument();
  });
});

// help-content.ts's step arrays can be reordered/edited independently of the
// manifest (positional-index keyed) — a mismatched stepTitle means the
// content moved since capture, so the page must fall back to text-only
// rather than pair a stale screenshot with a caption that no longer
// describes it (see help-screens-manifest.test.ts for the build-time guard
// against this same drift).
describe("GuidePage screenshot drift guard", () => {
  it("falls back to text-only when a manifest entry's stepTitle no longer matches the live step content", async () => {
    vi.doMock("@/lib/help-screens.manifest.json", () => ({
      default: {
        "record-consumption": {
          "1": {
            stepTitle: "Pick the Site", // stale — the real step 1 title is "Site"
            mobile: {
              image: "/help-screens/record-consumption/1.mobile.png",
              imageW: 390,
              imageH: 844,
              target: { x: 20, y: 300, w: 350, h: 44 },
            },
          },
        },
      },
    }));
    vi.resetModules();
    const { default: DriftedGuidePage } = await import("./page");

    render(await DriftedGuidePage({ params: Promise.resolve({ guideId: "record-consumption" }) }));

    expect(screen.queryByRole("img")).not.toBeInTheDocument();
    expect(screen.getByText("Site")).toBeInTheDocument();
    vi.doUnmock("@/lib/help-screens.manifest.json");
  });
});
