import Link from "next/link";
import { notFound } from "next/navigation";
import { HELP_CONTENT } from "@azentisfieldos/shared";
import { CheckCircleIcon, buttonVariants, cn } from "@azentisfieldos/ui";
import helpScreensManifest from "@/lib/help-screens.manifest.json";
import { GuideStepScreenshot, type HelpScreensManifest } from "../_components/guide-step-screenshot";

// Statically imported committed artifact (no runtime fs — safe under
// Vercel static prerender). Regenerated by `pnpm help:screens`; a guide or
// step with no entry renders text-only exactly as before the pipeline.
const HELP_SCREENS = helpScreensManifest as HelpScreensManifest;

// One visual step-by-step guide (EXPERIENCE.md Component Patterns → Guide
// step / Guide content source) — numbered cards read straight from
// HELP_CONTENT.guides, the same data the Client Presentation is generated
// from. The final step is always a real "Try it yourself" link into the
// live page it just taught (story 15.5-adjacent decision, confirmed with
// the Owner: a real link now, not a guided overlay).
export default async function GuidePage({ params }: { params: Promise<{ guideId: string }> }) {
  const { guideId } = await params;
  const guide = HELP_CONTENT.guides.find((g) => g.id === guideId);
  if (!guide) {
    notFound();
  }
  const guideModule = HELP_CONTENT.modules.find((m) => m.id === guide.moduleId);

  return (
    <div className="max-w-160">
      <div className="mb-2 text-eyebrow text-ink-500">
        <Link href="/help" className="hover:text-accent-teal-700 hover:underline">
          Help &amp; Guides
        </Link>{" "}
        / {guide.title}
      </div>
      <h1 className="mb-2 text-page-title text-ink-900">{guide.title}</h1>
      {guideModule ? <p className="mb-6 text-body-sm text-ink-500">{guideModule.whatIsIt}</p> : null}

      <ol className="flex flex-col gap-3">
        {guide.steps.map((step, i) => {
          // The manifest is keyed by positional index, not a stable step
          // identity — a guide-content edit (reorder/insert/reword a step)
          // desyncs a screenshot from its caption with no build-time signal.
          // stepTitle pins what title this capture was taken against; a
          // mismatch means the content moved since capture, so this falls
          // back to text-only rather than showing a screenshot ringing the
          // wrong field under a caption that no longer describes it.
          const rawCapture = HELP_SCREENS[guide.id]?.[String(i)];
          const capture = rawCapture?.stepTitle === step.title ? rawCapture : undefined;
          return (
            <li
              key={step.title}
              className="flex items-start gap-4 rounded-lg border border-border-hairline bg-surface-1 p-4 shadow-1"
            >
              <span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-accent-teal-700 text-body-sm font-bold text-white">
                {i + 1}
              </span>
              <div className="min-w-0 flex-1">
                <div className="text-card-title text-ink-900">{step.title}</div>
                <p className="mt-0.5 text-body-sm text-ink-500">{step.detail}</p>
                {capture ? (
                  <GuideStepScreenshot
                    entry={capture}
                    alt={`Screenshot of the app with "${step.title}" highlighted`}
                  />
                ) : null}
              </div>
            </li>
          );
        })}
      </ol>

      <div className="mt-4 flex items-center gap-2 rounded-md bg-success-100 p-3 text-body-sm font-semibold text-success-700">
        <CheckCircleIcon className="size-5 shrink-0" />
        {guide.result}
      </div>

      <Link href={guide.tryItHref} className={cn(buttonVariants({ variant: "primary" }), "mt-6")}>
        Try it yourself
      </Link>

      {guideModule ? (
        <div className="mt-10 rounded-lg border border-border-hairline bg-surface-2 p-5">
          <div className="mb-1 text-eyebrow uppercase text-ink-500">Real-life example</div>
          <p className="text-body-sm text-ink-700">{guideModule.example}</p>
        </div>
      ) : null}
    </div>
  );
}
